[package]
name = "append-only-vec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]

scaling = "0.1.3"
rand = "0.8"
parking_lot = "0.12"

[[bench]]
name = "bench"
harness = false
